language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

notifications:
  email: false

addons:
  apt:
    packages:
    - libfftw3-dev
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - libblas-dev
    - gfortran

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda

install:
    - conda install --yes nomkl
    - conda install --yes python=$TRAVIS_PYTHON_VERSION
    - conda install --yes future numpy scipy matplotlib pytest
    - pip install pyfftw
    - python setup.py install

script:
    - python setup.py test

deploy:
  provider: pypi
  user: brendt
  password:
    secure: O5sLpleEtN2bWsJIASUggQSy9QcLVEbe00Sp/rpxXep0NhoXjVSz0keDjk0XJxlbnb1/l1UXPg+vqSnfUNse8w0guAw+8gvGhhZAymgLqHv940dhuNt7rqlyOExbd2zb7Fu2PAt9dYtLOWEILTeqG2rLRj2TcHhL4m4e8OSN8I5NQ8taE7q11k+LwZj+REhAEE4WtHYXpfyc8BeFPqFXHorE5XoUvCQCIMH9BoGWF8CmAtQ6PeBi5e4IMSer3YEzrWg4IwyjuzwdlRiW/ZHCXCKqlMmlSY3/0bxMIiocBUff5PuDLsIWtn/8eR/CwLBoi1VWzLLq/RsHXp8BGOGvSRNAbCDYmgt7a1+ShmEqpojpLkgLhojl5jJfW9YXykKE+3LsnwlUqTpwrEkaFE/vHlh7EDcssYA7BKKJEeSCWKb46rKNfC2jIUdWEYbY5OMArnciNwhsLM6I1T1C86sAb9ppgzlITJDacLku8HIitMvRu29HBTNe8y9Is6/+T2MAGwUbxqxHKeOKm2/3GZGeojn0K8ZkQgCxbDGvLCVTL4k29tgii3sviM/2BgR58ixf4uLecR8PlPXFiCSCI7IYKQqEvMgO5LmmwgS1um85D9rCvqaF+zOyZLCmWIVA4DoHwsfGjfxe45v0pmt59iPDEcK7nQrou0ndeaMMAV2ksPo=
  on:
    tags: true
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
