language: python

python:
  - "2.7_with_system_site_packages"
  - "3.4"
  - "3.5"

notifications:
  email: false

addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - python-tk
    - python-matplotlib
    - libfftw3-dev
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - libblas-dev
    - gfortran

# command to install dependencies
install:
    - pip install future
    - pip install pyfftw
    - if [[ "${TRAVIS_PYTHON_VERSION}" != "2.7" ]]; then
        travis_wait pip install scipy;
        travis_wait pip install matplotlib;
      fi

# command to run tests
script:
    - python setup.py test

