language: python

python:
  - "2.7_with_system_site_packages"
  - "3.4"
  - "3.5"

notifications:
  email: false

addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - python-tk
    - python-matplotlib
    - libfftw3-dev
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - libblas-dev
    - gfortran

before_install:
    - if [[ "${TRAVIS_PYTHON_VERSION}" != "2.7" ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
        chmod +x miniconda.sh;
        ./miniconda.sh -b;
        export PATH=/home/travis/miniconda2/bin:$PATH;
        conda update --yes conda;
      fi

install:
    - pip install future
    - pip install pyfftw
    - if [[ "${TRAVIS_PYTHON_VERSION}" != "2.7" ]]; then
        conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib;
        python setup.py install;
      fi

script:
    - python setup.py test

