language: python

python:
  - "2.7_with_system_site_packages"
  - "3.4"
  - "3.5"

#virtualenv:
#    system_site_packages: true

addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - python-tk
    - python-matplotlib
    - libfftw3-dev

# command to install dependencies
install:
    - pip install future
    - pip install pyfftw

# command to run tests
script:
    - python setup.py test

