language: python

python:
  - "2.7"

virtualenv:
    system_site_packages: true
      - "2.7_with_system_site_packages"

addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - python-tk
    - python-matplotlib
    - libfftw3-dev

# command to install dependencies
install:
    - pip install pyfftw

# command to run tests
script:
    - python setup.py test

