language: python

python:
  - "2.7"

addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - python-matplotlib
    - libfftw3-dev

# command to install dependencies
install: "pip install pyfftw"

# command to run tests
script: py.test

